// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivVq019L8kY5k4qRZUfkVyIC_DXIFrYs',
    appId: '1:52373998804:web:ab1ce4a71fa8ea9cc03f41',
    messagingSenderId: '52373998804',
    projectId: 'zoom-clone-3eb6f',
    authDomain: 'zoom-clone-3eb6f.firebaseapp.com',
    storageBucket: 'zoom-clone-3eb6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDnJd6PrqH4UZS6g-YIo0hqwyNhhFXsmQ',
    appId: '1:52373998804:android:41fb58b4d62062a7c03f41',
    messagingSenderId: '52373998804',
    projectId: 'zoom-clone-3eb6f',
    storageBucket: 'zoom-clone-3eb6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm_6R6Xy-zu7T6nRG5bhade3K9BDBYLN0',
    appId: '1:52373998804:ios:1111a6b8a1ad1079c03f41',
    messagingSenderId: '52373998804',
    projectId: 'zoom-clone-3eb6f',
    storageBucket: 'zoom-clone-3eb6f.appspot.com',
    iosClientId: '52373998804-834n1jojnnvtqn6a9ai1rrf8ngc860ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm_6R6Xy-zu7T6nRG5bhade3K9BDBYLN0',
    appId: '1:52373998804:ios:1111a6b8a1ad1079c03f41',
    messagingSenderId: '52373998804',
    projectId: 'zoom-clone-3eb6f',
    storageBucket: 'zoom-clone-3eb6f.appspot.com',
    iosClientId: '52373998804-834n1jojnnvtqn6a9ai1rrf8ngc860ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
